# ============================================================================
# Shannon V3 Docker Compose Configuration
# ============================================================================
# Simplified orchestration for Shannon testing environment
# ============================================================================

version: '3.8'

services:
  # Shannon V3 testing environment
  shannon:
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    image: shannon:v3-testing
    container_name: shannon-test

    # Environment variables
    environment:
      - SHANNON_VERSION=3.0.0
      - TEST_MODE=docker
      - PYTHONUNBUFFERED=1

    # Mount test results for persistence
    volumes:
      - ./test-results:/app/shannon/test-results

    # Override default command for different test scenarios
    # Uncomment one of these or use `docker-compose run shannon <command>`
    # command: python3 -m pytest tests/ -v
    # command: python3 -m pytest tests/ --cov=Shannon --cov-report=html
    # command: python3 setup/install.py verify
    # command: /bin/bash  # Interactive shell

    # Restart policy (for long-running test scenarios)
    restart: "no"

    # Health check
    healthcheck:
      test: ["CMD", "python3", "setup/install.py", "verify"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

# ============================================================================
# Usage Examples
# ============================================================================
#
# Build and run tests:
#   docker-compose up --build
#
# Run specific test:
#   docker-compose run --rm shannon python3 -m pytest tests/test_shannon.py::test_name -v
#
# Interactive shell:
#   docker-compose run --rm shannon /bin/bash
#
# Verify installation:
#   docker-compose run --rm shannon python3 setup/install.py verify
#
# Show Shannon status:
#   docker-compose run --rm shannon python3 setup/install.py status
#
# Run with coverage:
#   docker-compose run --rm shannon python3 -m pytest tests/ --cov=Shannon --cov-report=html
#
# Clean up:
#   docker-compose down -v
#   docker rmi shannon:v3-testing
#
# ============================================================================