#!/bin/bash
# Shannon V3.1 Dashboard - Manual Testing Guide
#
# Run this script to test the dashboard interactively

echo "🎯 Shannon V3.1 Interactive Dashboard - Manual Test"
echo "================================================="
echo ""
echo "This will launch the dashboard with mock data."
echo "You can interact with it using your keyboard."
echo ""
echo "📋 Testing Checklist:"
echo ""
echo "Layer 1 (Session Overview):"
echo "  ✓ Verify goal is displayed"
echo "  ✓ Verify wave information shows"
echo "  ✓ Verify progress bar renders"
echo "  ✓ Verify agent summary appears"
echo "  ✓ Verify metrics display (cost, tokens, time)"
echo "  ✓ Press [Enter] to navigate to agents"
echo ""
echo "Layer 2 (Agent List):"
echo "  ✓ Verify table shows all 3 agents"
echo "  ✓ Press [1] [2] [3] to select different agents"
echo "  ✓ Verify selection highlighting works"
echo "  ✓ Press [Enter] to view agent detail"
echo ""
echo "Layer 3 (Agent Detail):"
echo "  ✓ Verify agent info header shows"
echo "  ✓ Verify context panel lists files, memory, tools, MCP"
echo "  ✓ Verify tool history panel shows file operations"
echo "  ✓ Press [t] to toggle tool history"
echo "  ✓ Press [c] to toggle context panel"
echo "  ✓ Press [Enter] to view messages"
echo ""
echo "Layer 4 (Message Stream):"
echo "  ✓ Verify messages are displayed"
echo "  ✓ Verify USER/ASSISTANT/TOOL syntax highlighting"
echo "  ✓ Press [↑] [↓] to scroll messages"
echo "  ✓ Press [Esc] to go back to Layer 3"
echo ""
echo "General:"
echo "  ✓ Press [h] to toggle help overlay"
echo "  ✓ Verify help shows correct shortcuts for each layer"
echo "  ✓ Press [q] to quit cleanly"
echo ""
echo "================================================="
echo ""
read -p "Press Enter to launch dashboard..." 

python test_dashboard_v31_live.py

